# syntax=docker/dockerfile:1.6.0
FROM ubuntu:23.10

# Install chrome => one layer
RUN \
    ["/bin/bash", "-c", "set -euxo pipefail \
    && apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests --yes  \
    curl \
    ca-certificates  \
    wget \
    gnupg \
    unzip \
    sudo  \
    build-essential \
    libx11-xcb1 \
    libgl1-mesa-dri \
    libcanberra-gtk-module  \
    libasound2 \
    init-system-helpers \
    " ]
ENV addr "deb http://dl.google.com/linux/chrome/deb/ stable main"

# Set the Chrome repo.
RUN \
    ["/bin/bash", "-c", "set -euxo pipefail", \
    " wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - " ,\
    " echo ${addr} >> /etc/apt/sources.list.d/google.list" \
    ]

# Set the Chrome repo.
RUN \
    ["/bin/bash", "-c", "set -euxo pipefail \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo \"deb http://dl.google.com/linux/chrome/deb/ stable main\" >> /etc/apt/sources.list.d/google.list \
    # Install Chrome.
    && apt-get update \
    && apt-get install --yes --no-install-recommends --no-install-suggests  google-chrome-stable \
    && apt-get --yes autoremove \
    && apt-get --yes clean \
    && rm -rf /var/lib/apt/lists/* \
    " ]







# install chromedriver

# ENV CHROME_VERSION = $(google-chrome  --product-version | awk '{print $1}' |awk -F. '{print $1}')
ENV CHROMEDRIVER_DIR=/chromedriver \
    DOWNLOAD_DIR=/DOWNLOAD

RUN set -e, -u, -x, -o pipefail; \ 
    mkdir ${CHROMEDRIVER_DIR} \
    && mkdir ${DOWNLOAD_DIR} \ 
    && curl --output ${DOWNLOAD_DIR}/chromedriver-linux64.zip  "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6045.159/linux64/chromedriver-linux64.zip" \
    && unzip ${DOWNLOAD_DIR}/chromedriver-linux64.zip -d ${CHROMEDRIVER_DIR}




#create user
ARG USER_NAME=default_user \
    USER_UID=1999 \
    USER_GID=$USER_UID

RUN set -e, -u, -x, -o pipefail; \
    && groupadd --gid $USER_GID $USER_NAME \
    && useradd --uid $USER_UID --gid $USER_GID --password $USER_NAME -m $USER_NAME \
    && echo "$USER_NAME:$USER_NAME" | chpasswd \
    && adduser $USER_NAME sudo 
# start services
# RUN update-rc.d dbus enable

# USER default_user
USER $USER_NAME

# add rust demo project
ENV RUST_PROJECT_DIR=/home/default_user/rust_work_space/tokio_finviz_shortput
# init cargo project
# change to home_directory
RUN set -e, -u, -x, -o pipefail; \
    &&  mkdir /home/$USER_NAME/rust_work_space \
    &&  cd $_ \
    &&  mkdir $RUST_PROJECT_DIR  \
    &&  cargo init $RUST_PROJECT_DIR  \
    &&  cd $RUST_PROJECT_DIR  \
    &&  cargo add tokio  \
    &&  cargo add tokio thirtyfour color-eyre sxd-document sxd-xpath table-extract  \
    &&  cargo build \
    &&  cargo run \
    &&  cd $RUST_PROJECT_DIR \
    &&  mkdir ./examples

# copy
COPY ./src/tokio_finviz.rs $RUST_PROJECT_DIR/examples/tokio_finviz.rs 

# add new entry to file e.g. Cargo.toml
# RUN tee -a /home/default_user/rust_work_space/tokio_finviz_shortput/Cargo.toml > /dev/null <<-"EOT" bash
# set -e, -u, -x ;
#
# [[example]]
# name = "tokio_finviz"
# EOT 

# FROM HERE
# https://www.docker.com/blog/introduction-to-heredocs-in-dockerfiles/
COPY <<EOF $RUST_PROJECT_DIR/Cargo.toml
#
[[example]]
name = "tokio_finviz"
EOF

RUN RUN set -e, -u, -x, -o pipefail; \
    && cd $RUST_PROJECT_DIR \
    && cargo build --example tokio_finviz

ENTRYPOINT ["/bin/bash"]
# ENTRYPOINT ["google-chrome","--no-sandbox","--disable-features=dbus"]
# --enable-unsafe-webgpu --enable-features=Vulkan --use-vulkan=swiftshader --use-webgpu-adapter=swiftshader --no-sandbox
# ENTRYPOINT ["set MESA_LOADER_DRIVER_OVERRIDE=\"i915\"","&&","google-chrome","--enable-unsafe-webgpu", "--enable-features=Vulkan","--use-vulkan=swiftshader","--use-webgpu","-adapter=swiftshader","--no-sandbox","--disable-features=dbus"]
# ENV MESA_LOADER_DRIVER_OVERRIDE=i915
# ENTRYPOINT ["google-chrome","--enable-unsafe-webgpu", "--enable-features=Vulkan","--use-vulkan=swiftshader","--use-webgpu","-adapter=swiftshader","--no-sandbox","--disable-features=dbus"]
