FROM ubuntu:23.10

RUN apt update \
&& apt-get install --no-install-recommends --yes wget unzip\
&& apt-get clean && rm -rf /var/lib/apt/lists/*

# ENV CHROME_VERSION = $(google-chrome  --product-version | awk '{print $1}' |awk -F. '{print $1}')
# ENV CHROME_VERSION=119
ENV CHROMEDRIVER_DIR=./chromedriver
RUN mkdir $CHROMEDRIVER_DIR
# RUN cd $CHROMEDRIVER_DIR

# https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6045.159/linux64/chromedriver-linux64.zip

RUN ["/bin/bash","wget","-q","--continue","-P $CHROMEDRIVER_DIR", "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6045.159/linux64/chromedriver-linux64.zip" ]
# RUN unzip $CHROMEDRIVER_DIR/chromedriver* -d $CHROMEDRIVER_DIR