FROM ubuntu:23.10

RUN apt update \
&& apt-get install --no-install-recommends --yes wget \
&& apt-get clean && rm -rf /var/lib/apt/lists/*

# ENV CHROME_VERSION = $(google-chrome  --product-version | awk '{print $1}' |awk -F. '{print $1}')
ENV CHROME_VERSION=119
ENV CHROMEDRIVER_DIR=./chromedriver
RUN mkdir $CHROMEDRIVER_DIR
RUN 


RUN unzip $CHROMEDRIVER_DIR/chromedriver* -d $CHROMEDRIVER_DIR