FROM ubuntu:23.10



# Install => one layer
RUN apt-get update \
    && apt-get install --no-install-recommends --yes wget ca-certificates gnupg sudo \
    # Set the Chrome repo.
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list \
    # Install Chrome.
    &&  apt-get update && apt-get --no-install-recommends --yes install google-chrome-stable \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

#create user
ARG USERNAME=default_user
ARG USER_UID=1999
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID --password $USERNAME -m $USERNAME \
    && echo "$USERNAME:$USERNAME" | chpasswd \
    && adduser $USERNAME sudo \
    # start services
    && update-rc.d dbus enable

# USER default_user
USER $USERNAME

ENTRYPOINT ["google-chrome","--no-sandbox","--disable-features=dbus"]